In [1]:
from pynwb import NWBFile
from neo import *
import pynwb
from pynwb import *
import quantities as pq
from quantities import s, ms,kHz, Hz, uV
import numpy as np
import random

In [2]:
# Define Neo blocks
bl0 = Block(name='First block')
bl1 = Block(name='Second block')
bl2 = Block(name='Third block')
original_blocks = [bl0, bl1, bl2]

num_seg = 1 #4  # number of segments
num_chan = 1 #3  # number of channels

size_x = 3
size_y = 2
num_frame = 3

for blk in original_blocks:

    for ind in range(num_seg):  # number of Segments
        seg = Segment(index=ind)
        seg.block = blk
        blk.segments.append(seg)

    for seg in blk.segments:  # AnalogSignal objects

        # 3 Neo AnalogSignals
        a = AnalogSignal(np.random.randn(44, num_chan) * pq.nA,
                                 sampling_rate=10 * pq.kHz,
                                 t_start=50 * pq.ms)
        
        # Image Sequence
        img_sequence_array = [[[column for column in range(size_x)]for row in range(size_y)] for frame in range(num_frame)]
        image_sequence = ImageSequence(img_sequence_array, 
                                       units='V',
                                       sampling_rate=1*pq.Hz, 
                                       spatial_scale=1*pq.micrometer,
                                       imaging_plane_excitation_lambda=3., # Value for NWB
                                       optical_channel_emission_lambda=3., # Value for NWB
                                       optical_channel_description='', # Value for NWB
                                       imaging_plane_description='', # Value for NWB
                                       imaging_plane_indicator='', # Value for NWB
                                       imaging_plane_location='', # Value for NWB
                                      )

        
        # Neo roi 
        roi = RectangularRegionOfInterest(1, 2, width=1.0, height=1.0)
        #roi = CircularRegionOfInterest(5, 5, radius=2)
        #roi = PolygonRegionOfInterest(
        #      (20.0, 20.0),
        #      (30.0, 20.0),
        #      (25.0, 25.0)
        #  )
        
        signal = image_sequence.signal_from_region(roi) # roi for Neo
        print("signal = ", signal)
  ###      seg.imagesequences.append(signal)
    
        seg.imagesequences.append(image_sequence)

        seg.analogsignals.append(a)
            
        a.segment = seg
        
        image_sequence.segment = seg

signal =  [<AnalogSignal(array([[2.],
       [2.],
       [2.]]) * V, [0.0 s, 3.0 s], sampling rate: 1.0 Hz)>]
signal =  [<AnalogSignal(array([[2.],
       [2.],
       [2.]]) * V, [0.0 s, 3.0 s], sampling rate: 1.0 Hz)>]
signal =  [<AnalogSignal(array([[2.],
       [2.],
       [2.]]) * V, [0.0 s, 3.0 s], sampling rate: 1.0 Hz)>]


In [3]:
blk

Block with 1 segments
name: 'Third block'
# segments (N=1)
0: Segment with 1 analogsignals, 1 imagesequences
   # analogsignals (N=1)
   0: AnalogSignal with 1 channels of length 44; units nA; datatype float64 
      sampling rate: 10.0 kHz
      time: 50.0 ms to 54.4 ms
   # imagesequences (N=1)
   0: ImageSequence 3 frames with width 3 px and height 2 px; units V; datatype int64 
      sampling rate: 1.0 Hz
      spatial_scale: 1.0 um

In [4]:
test_file_name = "test_write_Fluorescence_NWB.nwb"
iow = NWBIO(filename=test_file_name, mode='w')
iow.write_all_blocks([blk])
print("iow = ", iow)

/Users/legouee/miniconda3/envs/test_nwb/lib/python3.8/site-packages/pynwb/file.py:801: UserWarning: Date is missing timezone information. Updating to local timezone.
  warn("Date is missing timezone information. Updating to local timezone.")
/Users/legouee/miniconda3/envs/test_nwb/lib/python3.8/site-packages/hdmf/build/objectmapper.py:653: MissingRequiredBuildWarning: TwoPhotonSeries 'name images_series_Neo Third block : segment0 : image0' is missing required value for attribute 'unit'.
  warnings.warn(msg, MissingRequiredBuildWarning)


iow =  <neo.io.nwbio.NWBIO object at 0x11ffbc910>


In [5]:
iow

In [6]:
ior = NWBIO(filename=test_file_name, mode='r')

In [7]:
print("ior = ", ior)

ior =  <neo.io.nwbio.NWBIO object at 0x11ffbc1c0>


In [8]:
retrieved_block = ior.read_all_blocks()

In [9]:
print("retrieved_block = ", retrieved_block)

retrieved_block =  [<neo.core.block.Block object at 0x11ffbc8e0>, <neo.core.block.Block object at 0x12057b2b0>]


In [10]:
for i in retrieved_block:
    for j in i.segments:
        print("j.imagesequences = ", j.imagesequences)
        #print("   ")
        print("j.__dict__ = ", j.__dict__)

j.imagesequences =  []
j.__dict__ =  {'annotations': {}, 'name': 'Third block : segment0', 'description': None, 'file_origin': None, 'block': <neo.core.block.Block object at 0x11ffbc8e0>, 'analogsignals': [<AnalogSignal(array([[-0.19965639],
       [ 0.30266149],
       [-1.72627415],
       [ 0.52448039],
       [ 0.3889745 ],
       [-0.96625074],
       [-0.8730737 ],
       [-1.17040857],
       [-1.12297813],
       [-0.36404887],
       [-1.35244971],
       [-0.27225003],
       [ 0.36334813],
       [-0.41183706],
       [-0.52676457],
       [ 0.40572082],
       [ 0.20989322],
       [-1.98805847],
       [-0.17144313],
       [ 1.77931133],
       [ 0.80744393],
       [ 1.25682102],
       [-0.72861577],
       [ 1.19012487],
       [-0.86555697],
       [ 1.25423022],
       [-0.99107681],
       [-0.68106922],
       [ 2.61640485],
       [ 0.89558839],
       [-0.38297682],
       [ 1.00779731],
       [-0.93805838],
       [-0.29155956],
       [-0.34267913],
       [-0

In [11]:
# access to segments
for seg in blk.segments:
    print("seg = ", seg)
    for img in seg.imagesequences:
        print("img = ", img)
        print("img.__dict__ = ", img.__dict__)
        print("---")


seg =  <neo.core.segment.Segment object at 0x11ff9d490>
img =  [[[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]] V
img.__dict__ =  {'_dimensionality': Dimensionality({volt: 1}), 'annotations': {'imaging_plane_excitation_lambda': 3.0, 'optical_channel_emission_lambda': 3.0, 'optical_channel_description': '', 'imaging_plane_description': '', 'imaging_plane_indicator': '', 'imaging_plane_location': ''}, 'array_annotations': {}, 'name': 'Third block : segment0 : image0', 'file_origin': None, 'description': None, 'segment': <neo.core.segment.Segment object at 0x11ff9d490>, 'sampling_rate': array(1.) * Hz, 'spatial_scale': array(1.) * um, '_t_start': array(0.) * s}
---


In [12]:
read = ior.read()

In [13]:
read

[Block with 1 segments
 name: 'Third block'
 description: 'test_write_Fluorescence_NWB.nwb'
 annotations: {'session_start_time': datetime.datetime(2021, 9, 13, 12, 15, 58, 661541, tzinfo=tzoffset(None, 7200)),
   'identifier': 'test_write_Fluorescence_NWB.nwb',
   'timestamps_reference_time': datetime.datetime(2021, 9, 13, 12, 15, 58, 661541, tzinfo=tzoffset(None, 7200)),
   'session_description': 'test_write_Fluorescence_NWB.nwb'}
 file_origin: 'test_write_Fluorescence_NWB.nwb'
 rec_datetime: datetime.datetime(2021, 9, 13, 12, 15, 58, 661541, tzinfo=tzoffset(None, 7200))
 # segments (N=1)
 0: Segment with 1 analogsignals
    name: 'Third block : segment0'
    # analogsignals (N=1)
    0: AnalogSignal with 1 channels of length 44; units nA; datatype float64 
       name: 'Third block : segment0 : analogsignal0 0'
       description: 'no description'
       annotations: {'sweep_number': None,
         'nwb_group': 'acquisition',
         'nwb:resolution': -1.0,
         'nwb:conversion'