In [1]:
from pynwb import NWBFile
from datetime import datetime
from dateutil import tz

import neo
from neo import *
import pynwb
from pynwb import *
import quantities as pq
from quantities import s, ms, kHz, Hz, uV
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

from os.path import exists
from urllib.request import urlretrieve

# Write a NWB file with Neo NWBIO

In [2]:
filename="Example_Write_Neo_NWB_File.nwb"
iow = NWBIO(filename, mode='w')
iow

In [3]:
# Define Neo blocks
bl0 = Block(name='First block')
bl1 = Block(name='Second block')
bl2 = Block(name='Third block')
original_blocks = [bl0, bl1, bl2]

num_seg = 2  # number of segments
num_chan = 3  # number of channels

size_x = 3
size_y = 2
num_frame = 3

for blk in original_blocks:

    for ind in range(num_seg):  # number of Segments
        seg = Segment(index=ind)
        seg.block = blk
        blk.segments.append(seg)

    for seg in blk.segments:  # AnalogSignal objects

                # 3 Neo AnalogSignals
        a = AnalogSignal(np.random.randn(44, num_chan) * pq.nA,
                                 sampling_rate=10 * pq.kHz,
                                 t_start=50 * pq.ms)
        b = AnalogSignal(np.random.randn(64, num_chan) * pq.mV,
                                 sampling_rate=8 * pq.kHz,
                                 t_start=40 * pq.ms)
        c = AnalogSignal(np.random.randn(33, num_chan) * pq.uA,
                                 sampling_rate=10 * pq.kHz,
                                 t_start=120 * pq.ms)

                # 2 Neo IrregularlySampledSignals
        d = IrregularlySampledSignal(np.arange(7.0)*pq.ms,
                                             np.random.randn(7, num_chan)*pq.mV)

                # 2 Neo SpikeTrains
        train = SpikeTrain(times=[1, 2, 3] * pq.s, t_start=1.0, t_stop=10.0)
        train2 = SpikeTrain(times=[4, 5, 6] * pq.s, t_stop=10.0)

                # 1 Neo Event
        evt = Event(times=np.arange(0, 30, 10) * pq.ms,
                            labels=np.array(['ev0', 'ev1', 'ev2']))

                # 2 Neo Epochs
        epc = Epoch(times=np.arange(0, 30, 10) * pq.s,
                            durations=[10, 5, 7] * pq.ms,
                            labels=np.array(['btn0', 'btn1', 'btn2']))

        epc2 = Epoch(times=np.arange(10, 40, 10) * pq.s,
                             durations=[9, 3, 8] * pq.ms,
                             labels=np.array(['btn3', 'btn4', 'btn5']))

                # Image Sequence
        img_sequence_array = [[[column for column in range(size_x)]for row in range(size_y)] for frame in range(num_frame)]
        print("img_seguence_array = ", img_sequence_array)
        image_sequence = ImageSequence(img_sequence_array, 
                                       units='V',
                                       sampling_rate=1*pq.Hz, 
                                       spatial_scale=1*pq.micrometer,
                                       imaging_plane_excitation_lambda=3., # Value for NWB
                                       optical_channel_emission_lambda=3., # Value for NWB
                                       optical_channel_description='', # Value for NWB
                                       imaging_plane_description='', # Value for NWB
                                       imaging_plane_indicator='', # Value for NWB
                                       imaging_plane_location='', # Value for NWB
                                      )
        print("image_sequence = ", image_sequence)

        seg.imagesequences.append(image_sequence)
        
        seg.spiketrains.append(train)
        seg.spiketrains.append(train2)

        seg.epochs.append(epc)
        seg.epochs.append(epc2)

        seg.analogsignals.append(a)
        seg.analogsignals.append(b)
        seg.analogsignals.append(c)
            
        seg.irregularlysampledsignals.append(d)
            
        seg.events.append(evt)
            
        a.segment = seg
        b.segment = seg
        c.segment = seg
        d.segment = seg
        evt.segment = seg
        train.segment = seg
        train2.segment = seg
        epc.segment = seg
        epc2.segment = seg
        image_sequence.segment = seg

img_seguence_array =  [[[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]]]
image_sequence =  [[[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]] V
img_seguence_array =  [[[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]]]
image_sequence =  [[[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]] V
img_seguence_array =  [[[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]]]
image_sequence =  [[[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]] V
img_seguence_array =  [[[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]]]
image_sequence =  [[[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]] V
img_seguence_array =  [[[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]]]
image_sequence =  [[[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]] V
img_seguence_array =  [[[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]], [[0, 1, 2], [0, 1, 2]]]


In [4]:
iow.write_all_blocks(original_blocks)

/Users/legouee/miniconda3/lib/python3.7/site-packages/pynwb/file.py:753: UserWarning: Date is missing timezone information. Updating to local timezone.
  warn("Date is missing timezone information. Updating to local timezone.")
/Users/legouee/miniconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py:769: MissingRequiredWarning: attribute 'unit' for 'data' (TwoPhotonSeries)
  warnings.warn(msg, MissingRequiredWarning)


## Read this file, with PyNWB

In [5]:
io_pynwb = pynwb.NWBHDF5IO("Example_Write_Neo_NWB_File.nwb", mode='r')
print("io_pynwb = ", io_pynwb)
print("pynwb.__version__ = ", pynwb.__version__)

io_pynwb =  <pynwb.NWBHDF5IO object at 0x122177950>
pynwb.__version__ =  1.4.0


In [6]:
data = io_pynwb.read()

In [7]:
data.acquisition

{'First block : segment0 : analogsignal0 0': First block : segment0 : analogsignal0 0 pynwb.base.TimeSeries at 0x4875781904
 Fields:
   comments: {"block": "First block", "segment": "First block : segment0"}
   conversion: 1.0
   data: <HDF5 dataset "data": shape (44, 3), type "<f8">
   description: no description
   rate: 10000.0
   resolution: -1.0
   starting_time: 0.05
   starting_time_unit: seconds
   unit: nA,
 'First block : segment0 : analogsignal1 1': First block : segment0 : analogsignal1 1 pynwb.base.TimeSeries at 0x4875782416
 Fields:
   comments: {"block": "First block", "segment": "First block : segment0"}
   conversion: 1.0
   data: <HDF5 dataset "data": shape (64, 3), type "<f8">
   description: no description
   rate: 8000.0
   resolution: -1.0
   starting_time: 0.04
   starting_time_unit: seconds
   unit: mV,
 'First block : segment0 : analogsignal2 2': First block : segment0 : analogsignal2 2 pynwb.base.TimeSeries at 0x4875783056
 Fields:
   comments: {"block": "Firs

## Write a new NWB file with PyNWB

In [8]:
from pynwb import NWBFile
from datetime import datetime
from dateutil import tz

session_start_time = datetime.now()

nwbfile = NWBFile(
    session_description='Description',
    identifier='Mouse',
    session_start_time=session_start_time,
)
print(nwbfile)

root pynwb.file.NWBFile at 0x4871680400
Fields:
  file_create_date: [datetime.datetime(2021, 3, 29, 14, 33, 38, 657549, tzinfo=tzlocal())]
  identifier: Mouse
  session_description: Description
  session_start_time: 2021-03-29 14:33:38.655890+02:00
  timestamps_reference_time: 2021-03-29 14:33:38.655890+02:00



In [9]:
from pynwb.device import Device
from pynwb.ophys import OpticalChannel

device = nwbfile.create_device(
    name='Microscope', 
    description='My two-photon microscope',
    manufacturer='The best microscope manufacturer'
)
optical_channel = OpticalChannel(
    name='OpticalChannel', 
    description='an optical channel', 
    emission_lambda=500.
)
imaging_plane = nwbfile.create_imaging_plane(
    name='ImagingPlane',
    optical_channel=optical_channel,
    imaging_rate=30.,
    description='a very interesting part of the brain',
    device=device,
    excitation_lambda=600.,
    indicator='GFP',
    location='V1',
    grid_spacing=[.01, .01],
    grid_spacing_unit='meters',
    origin_coords=[1., 2., 3.],
    origin_coords_unit='meters'
)

In [10]:
from pynwb.ophys import TwoPhotonSeries
import numpy as np

image_series = TwoPhotonSeries(
    name='TwoPhotonSeries1',
    data=np.ones((2,3,4)),
    imaging_plane=imaging_plane,
    rate=1.0,
    unit='normalized amplitude'
)

print(image_series)

TwoPhotonSeries1 pynwb.ophys.TwoPhotonSeries at 0x4871680080
Fields:
  comments: no comments
  conversion: 1.0
  data: [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
  description: no description
  imaging_plane: ImagingPlane pynwb.ophys.ImagingPlane at 0x4871681552
Fields:
  conversion: 1.0
  description: a very interesting part of the brain
  device: Microscope pynwb.device.Device at 0x4871682896
Fields:
  description: My two-photon microscope
  manufacturer: The best microscope manufacturer

  excitation_lambda: 600.0
  imaging_rate: 30.0
  indicator: GFP
  location: V1
  optical_channel: (
    OpticalChannel <class 'pynwb.ophys.OpticalChannel'>
  )
  unit: meters

  rate: 1.0
  resolution: -1.0
  starting_time: 0.0
  starting_time_unit: seconds
  unit: normalized amplitude



In [11]:
nwbfile.add_acquisition(image_series)

In [12]:
from pynwb import NWBHDF5IO

with NWBHDF5IO('Example_Write_NWB_Neo_File.nwb', 'w') as io:
    io.write(nwbfile)

## Read this file with Neo NWBIO

In [13]:
ior2 = NWBIO("Example_Write_NWB_Neo_File.nwb", mode='r')
blktest = ior2.read_all_blocks()
print("blktest = ", blktest)

blktest =  [<neo.core.block.Block object at 0x12260fed0>]


In [14]:
blktest[0].segments[0].__dict__

{'annotations': {},
 'name': 'default',
 'description': None,
 'file_origin': None,
 'block': Block with 1 segments
 name: 'default'
 description: 'Description'
 annotations: {'session_start_time': datetime.datetime(2021, 3, 29, 14, 33, 38, 655890, tzinfo=tzoffset(None, 7200)),
   'identifier': 'Mouse',
   'timestamps_reference_time': datetime.datetime(2021, 3, 29, 14, 33, 38, 655890, tzinfo=tzoffset(None, 7200)),
   'session_description': 'Description'}
 file_origin: 'Example_Write_NWB_Neo_File.nwb'
 rec_datetime: datetime.datetime(2021, 3, 29, 14, 33, 38, 655890, tzinfo=tzoffset(None, 7200))
 # segments (N=1)
 0: Segment with 1 imagesequences
    name: 'default'
    # analogsignals (N=0)
    # imagesequences (N=1)
    0: ImageSequence 2 frames with width 3 px and height 4 px; units m; datatype int64 
       sampling rate: 30.0 Hz
       spatial_scale: No spatial_scale,
 'analogsignals': [],
 'epochs': [],
 'events': [],
 'irregularlysampledsignals': [],
 'spiketrains': [],
 'imageseq